name: Auto Update VPN Chain

on:
  schedule:
    - cron: '0 * * * *' # Запуск каждый час (можно поменять)
  workflow_dispatch: # Позволяет запускать вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: python parser.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@://github.com"
        git add "config.json"
        git commit -m "Автообновление конфигурации цепочки" || echo "Нет изменений для коммита"
        git push
